name: cos_sim.py


on: [push]

jobs:
  cos_sim_test:
    runs-on: [self-hosted, Linux, test]
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls -lah
      - name: check dependencies
        run: |
          pip freeze
      - name: cos_sim.py test
        run: python3 cos_sim.py
