name: cos_sim.py test

on: [push]

jobs:
  vim_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls -lah
      - name: cos_sim.py test
        run: python3 cos_sim.py
