name: cos_sim.py

# 시작 해볼게요.

on: [push]

jobs:
  cos_sim_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ls
        run: ls -lah
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: check dependencies
        run: |
          pip freeze
      - name: cos_sim.py test
        run: python3 cos_sim.py
